### ISSUE TITLE
Toggles for the different randomizations

### ISSUE THREAD

**Issue by GamingInfinite** [MelonSpeedruns/BotwRandomizer#1]
I know this is probably gonna be something implemented down the line, but being able to randomize only enemies, or only items, or only specific item pools would be great.  This would also allow for options like randomizing the camp kill chests, and also for some chaos options such as randomizing koroks or randomizing the runes to be in random places (but not the paraglider for obvious reasons, until a way to remove the paraglider barrier is found via mods, unless that can already be done in which case why hasn't it been created yet).

**Comment by MelonSpeedruns** [comment]
My code is in a serious need of refactoring, but I was indeed considering a list where you can toggle certain elements. And that list would dictact where the Spirit Orbs could be placed in.

**Comment by RevanXVIV** [comment]
Could you also add a toggle for clothes to be in any chest? It'd be nice to be able to find somewhat decent armor anywhere in the game.

**Comment by DaemonCrusher1** [comment]
> My code is in a serious need of refactoring, but I was indeed considering a list where you can toggle certain elements. And that list would dictact where the Spirit Orbs could be placed in.

You’ve probably thought about this, but would this also include placing spirit orbs in skull chests? (the locked ones in enemy camps).
There are about (I think) 54 skull chests in the overworld, including the chest with Hestu’s Maracas.
If you haven’t thought about it, I will suggest this either way, as it would make for a different and challenging playing experience, having to defeat enemy camps to get the Master Sword.

**Comment by MelonSpeedruns** [comment]
This was added in the latest push that made everything C# !
