### ISSUE TITLE
Windows Smartscren as well as many other av's are detecting the tool as a virus 

### ISSUE THREAD

**Issue by pokeyjojo** [MelonSpeedruns/BotwRandomizer#14]
The tool used to randomize the game is being flagged by 5 engines virustotal say that the tool is a trojan downloader,  it is also flagged by windows smartscreen and chrome was blocking the file when downloaded  I understand that its false positive because its open source but is there any sort of way that you can get rid of them? i dont know how coding works but it seems like something that would be useful. And do you know what part of the tool is getting flagged as a virus?

**Comment by MelonSpeedruns** [comment]
Try the newest C# code I pushed to the repository, if you build it yourself, it shouldn't flag it as a virus!

**Comment by Miepee** [comment]
Try checking it again with 2.0

**Comment by pokeyjojo** [comment]
2.1 not being flagged by anything!
