### ISSUE TITLE
"-" character in the graphicPack folder path results in crash

### ISSUE THREAD

**Issue by Pandatron76** [MelonSpeedruns/BotwRandomizer#15]
### Brief Description

If the user's path for the "Cemu Graphic Pack Folder" includes the character "-" and they attempt to randomize a game, the "BOTW Randomizer Tool" will attempt to generate a game but will crash on the "Randomizing Overworld" step.

### Steps to Reproduce
 - Open BOTW Randomizer Tool.
 - Populate the "BOTW Base Content Folder", "BOTW Update Content Folder" and "BOTW DLC Content Folder" via their respective "Browse..." buttons.
 - Populate the "Cemu Graphic Packs Folder" via the browse button and make sure the file path includes a "-" character.

### Result
- "BOTW Randomizer Tool" crashes with no lingering traces of a background process running.

### Discord Info
Pandatron76#8419

### Additional Information
- Thanks for providing this tool for the community, I got it working and definitely looking forward to giving this a go over the next few days :) .
- This appears to be happening for myself and I expect also for Fungyfarmer in Discord as well https://discord.com/channels/888554960931946528/906199628943360061/914543670227787827 .
 - The "-" issue does not not appear to be the case with the "BOTW Base Content Folder", "BOTW Update Content Folder" and "BOTW DLC Content Folder".
 - Running the tool on Windows 10 with latest non-experimental version of Python3.
 - It appears to work well with other similar (ish) characters like "_" and ".".
 - Please let me know if you have any questions and my apologies if this is a misreporting. Wasn't sure if reporting potential issues should be done via a GitHub issue and/or via the Discord.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/42257216/144074014-e38a9a32-ef9a-4f2d-a5ab-1cea4fdc9dec.png)

**Comment by MelonSpeedruns** [comment]
Thanks for the report! Try with the latest C# code that I just pushed, it fixes that!
