### ISSUE TITLE
not getting camera rune in game 

### ISSUE THREAD

**Issue by pokeyjojo** [MelonSpeedruns/BotwRandomizer#17]
after loading up the  game and playing. i do not get the camera rune, however when i watched linkus7's video he got the camera rune right when he walked out of the shrine of resurrection i do not know how to reproduce and dont know how to fix this.

**Comment by Miepee** [comment]
~~You should be able to use the camera rune after getting your first rune.~~
Did you press `Minus`, `L` and then `A` on the camera?

**Comment by pokeyjojo** [comment]
managed to fix after selecting from shieka menu! thanks!
