### ISSUE TITLE
dotnet error

### ISSUE THREAD

**Issue by BurritoHangover** [MelonSpeedruns/BotwRandomizer#19]
ok so, when i run the program, it says, "To install this randomizer, you must install the missing frameworks"
and i already installed them and it wont let me run the program
please help

**Comment by LivesEquils9** [comment]
Is it the dotNET Desktop Runtime that you have installed because if not you need it and make sure its the latest release

**Comment by MelonSpeedruns** [comment]
Install exactly this: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.0-windows-x64-installer
