### ISSUE TITLE
Costumes seem to have a minor issue

### ISSUE THREAD

**Issue by RevanXVIV** [MelonSpeedruns/BotwRandomizer#7]
Ok so I've played this for about 8 hours today, and one thing I noticed was that Helmets, torsos, and pants only came from "clothing chests" instead of any chest. Is this intentional or a bug?

**Comment by MelonSpeedruns** [comment]
It is intentional yes!

**Comment by RevanXVIV** [comment]
Any chance for an option in a future update to have it where costume pieces can be anywhere? It'd make the game a little more interesting rather than just constantly getting arrow bundles or gems.

**Comment by MelonSpeedruns** [comment]
A "Everything is completely random" option could definitely be added later down the line.
